# Generated by Django 3.2.14 on 2025-06-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('Gemini', 'Gemini'), ('OpenAI', 'OpenAI')], max_length=20)),
                ('model_name', models.CharField(default='Gemini', max_length=100)),
                ('prompt_text', models.TextField()),
            ],
        ),
    ]
